development:
    adapter: postgresql
    database: fragment_dev
    username: fragment
    password: fragfrag
    pool: 5
    timeout: 5000

test:
    adapter: postgresql
    database: fragment_test
    username: fragment
    password: fragfrag
    pool: 5
    timeout: 5000

production:
    adapter: postgresql
    database: fragment
    username: fragment
    password: fragfrag
    pool: 5
    timeout: 5000